openapi: 3.0.1
info:
  title: rec-admin
  version: 0.0.1
servers:
  - url: 'http://localhost:7220/api'
    description: Development server
  - url: 'https://localhost:7220/api'
    description: Development server with TLS Profile
paths:
  /featured-first/top/add:
    parameters: []
    post:
      summary: /featured-first/top/add
      operationId: post-featured-first-top-add
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/RecOpConfigDto.v1.yaml
      description: 信息流场景-新建置顶
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/RecOpConfigDto.v1.yaml
  /featured-first/single-heavy/add:
    parameters: []
    post:
      summary: /featured-first/single-heavy/add
      operationId: post-featured-first-single-heavy-add
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/RecOpConfigDto.v1.yaml
      description: 信息流场景-新建重磅单品
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/RecOpConfigDto.v1.yaml
  /featured-first/column-heavy/add:
    post:
      summary: /featured-first/column-heavy/add
      operationId: post-featured-first-column-heavy-add
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/RecOpConfigDto.v1.yaml
      description: 信息流场景-新建重磅栏目
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/RecOpConfigDto.v1.yaml
    parameters: []
components:
  schemas: {}
